name: Rust Project Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - '*'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache APT packages and lists
        id: cache-apt
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: APT cache hit message
        if: steps.cache-apt.outputs.cache-hit == 'true'
        run: echo 'APT CACHE HIT: APT PACKAGES RESTORED FROM CACHE'

      - name: Cache Cargo registry
        id: cache-cargo-registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cargo registry cache hit message
        if: steps.cache-cargo-registry.outputs.cache-hit == 'true'
        run: echo 'CARGO REGISTRY CACHE HIT: CARGO REGISTRY RESTORED FROM CACHE'

      - name: Cache Rust toolchain
        id: cache-rust-toolchain
        uses: actions/cache@v3
        with:
          path: ~/.rustup/toolchains
          key: ${{ runner.os }}-rust-toolchain-${{ hashFiles('rust-toolchain') }}
          restore-keys: |
            ${{ runner.os }}-rust-toolchain-

      - name: Rust toolchain cache hit message
        if: steps.cache-rust-toolchain.outputs.cache-hit == 'true'
        run: echo 'RUST TOOLCHAIN CACHE HIT: RUST TOOLCHAIN RESTORED FROM CACHE'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
    
      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Build
        run: cargo build --verbose

      # - name: Run unit tests
      #   run: cargo test --workspace --verbose

      - name: Run `express` example
        run: cargo run --example express --release --quiet
