name: Rust Project Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - ´*´

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      # Use Github Actions logic
      - uses: actions/checkout@v3

      # Cache installs
      - name: Cache APT packages and lists
        uses: actions/cache@v3
        with:
          path: |
            /var/cache/apt
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Rust toolchain
        uses: actions/cache@v3
        with:
          path: ~/.rustup/toolchains
          key: ${{ runner.os }}-rust-toolchain-${{ hashFiles('rust-toolchain') }}
          restore-keys: |
            ${{ runner.os }}-rust-toolchain-

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev graphviz

      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      # Install cargo package cargo-depgraph
      - name: Install cargo-depgraph
        run: cargo install cargo-depgraph
        
      # Set terminal 
      - name: Set up terminal
        run: echo "TERM=xterm" >> $GITHUB_ENV

  lint:
    steps:
    # Prepare code
    - name: Format the code
      run: make prep

  test:
    steps:
    # Run tests
    - name: Run tests
      run: cargo test
